import Link from 'next/link';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { newsContent } from 'translations/content';

const Home = ({ toggleTheme, isDarkTheme }: { toggleTheme: () => void; isDarkTheme: boolean }) => {
	const { locale, asPath } = useRouter();

	const { title, content } = newsContent[locale];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<span>Current Language: </span>
				<span
					style={{
						borderRadius: '3px',
						backgroundColor: 'blue',
						color: 'white',
						padding: '2px',
					}}
				>
					{locale}
				</span>
				<div>
					<Link href={asPath} locale="pl">
						pl
					</Link>

					<Link href={asPath} locale="en">
						en
					</Link>
				</div>
				<span
					style={{
						borderRadius: '3px',
						backgroundColor: 'blue',
						color: 'white',
						padding: '2px',
					}}
				>
					{title}
				</span>

				<button onClick={toggleTheme} type="button">
					{isDarkTheme ? (
						<span aria-label="Light mode" role="img">
							🌞
						</span>
					) : (
						<span aria-label="Dark mode" role="img">
							🌜
						</span>
					)}
				</button>
			</main>
		</>
	);
};

export default Home;
